config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :products
  resources :orders, only: [:index,:show, :new ]
  post '/purchase' => 'orders#purchase_status'
  get '/refund/:id', to: 'orders#refund'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  include Razorpay
  belongs_to :product
  belongs_to :user
[:authorized, :captured, :refunded, :error].each do |scoped_key|
    scope scoped_key, -> { where('LOWER(status) = ?', scoped_key.to_s.downcase) }
  end

  class << self
    def process_razorpayment(params)
      Razorpay.setup("rzp_test_dx0TmeNH8tldL8", "Ds0B2l0lPJO1idceUIslurN7")
      puts "params", params
      product = Product.find(params[:product_id])
      puts "product", product
      razorpay_pmnt_obj = Razorpay::Payment.fetch(params[:payment_id])
      puts razorpay_pmnt_obj.id
      puts razorpay_pmnt_obj.status 
      status = razorpay_pmnt_obj.status
      if status == "authorized"
        puts "ok1"
        Razorpay::Payment.fetch(params[:payment_id]).capture({amount: product.price * 100})
        puts "ok"
        razorpay_pmnt_obj = Razorpay::Payment.fetch(params[:payment_id])
        params.merge!({method:razorpay_pmnt_obj.method, status: razorpay_pmnt_obj.status, amount: product.price, error:razorpay_pmnt_obj.error_description})
        puts "newparams", params
        Order.create(params)
      else 
      	raise StandardError, "Unable to capture payment"
      end
    end

    def process_refund(payment_id)
      Razorpay.setup("rzp_test_dx0TmeNH8tldL8", "Ds0B2l0lPJO1idceUIslurN7")
      Razorpay::Payment.fetch(payment_id).refund
      record = Order.find_by_payment_id(payment_id)
      record.update_attributes(status: Razorpay::Payment.fetch(payment_id).status)
      record
    end

  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def purchase_status
    begin
      @order = Order.process_razorpayment(order_params)
      redirect_to :action => "show", :id => @order.id
    rescue Exception
      flash[:notice] = "Unable to process payment."
      redirect_to root_path
    end
  end

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find_by_id(params[:id])
  end

  def refund
    payment_id = Order.find_by_id(params[:id]).payment_id
    @order = Order.process_refund(payment_id)
    redirect_to :action => "show", :id => @order.id
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
       p = params.permit(:razorpay_payment_id, :payment_id, :method, :amount, :status, :error, :product_id, :user_id)
       p.merge!({payment_id: p.delete(:razorpay_payment_id) || p[:payment_id]})
       p
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header class="navbar">
  <% if signed_in? %>
  <nav>
    <ul class="nav nav-tabs">
      <li class="nav-link"><%= link_to "Home", root_path%></li> 
      <li class="nav-link"><%= link_to "Products", controller: 'products'%></li> 
      <li class="nav-link"><%= link_to "Orders", controller: 'orders'%></li> 
      <li class="nav-link"> <%= link_to 'Logout', sign_out_path, method: :delete %>
    </ul>
    </nav>
      Signed in as: <%= current_user.email %>
    <% else %>
      <nav>
      <ul class="nav nav-tabs">
        <li class="nav-link"><%= link_to "Home", root_path%></li> 
        <li class="nav-link"> <%= link_to 'Login', sign_in_path %>
      </ul>
  </nav>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RozerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    <%=render "layouts/header"%>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th>Amount</th>
      <th>Payment</th>
      <th>Method</th>
      <th>Status</th>
      <!-- <th>Error</th> -->
      <th>Refund</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user.email %></td>
        <td><%= order.product.name %></td>
        <td><%= order.amount %></td>
        <td><%= link_to "#{order.payment_id}", order %></td>
        <td><%= order.method %></td>
        <td><%= order.status %></td>
        <!-- <td><%= order.error %></td> -->
        <%if order.status == "captured" %>
          <td><%= link_to "refund", action:"refund", id: order.id %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payment:</strong>
  <%= @order.payment_id %>
</p>

<p>
  <strong>Method:</strong>
  <%= @order.method %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @order.amount %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<!-- <p>
  <strong>Error:</strong>
  <%= @order.error %>
</p> -->

<p>
  <strong>Product:</strong>
  <%= @order.product.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user.email %>
</p>

<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td>&#8377; <%= product.price %></td>
        <td>
          <form action="/purchase" method="POST">
          <!-- Note that the amount is in paise = 50 INR -->
          <script
            src="https://checkout.razorpay.com/v1/checkout.js"
            data-key="rzp_test_dx0TmeNH8tldL8"
            data-amount="<%= "#{product.price * 100}" %>"
            data-buttontext="Pay"
            data-name="<%= "#{product.name}" %>"
            data-description="<%= "#{product.description}" %>"
            data-image="https://s3.ap-south-1.amazonaws.com/rzp-prod-merchant-assets/payment-link/description/burger-logo_C44radRsyNLxbm.png"
            data-prefill.name="Gaurav Kumar"
            data-prefill.email="<%= "#{current_user.email}" %>"
            data-theme.color="#198F69">
          </script>
          <input type="hidden" value="<%= "#{product.id}" %>" name="product_id">
          <input type="hidden" value="<%= "#{current_user.id}" %>" name="user_id">
          </form>
        </td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>